### ISSUE TITLE
[feature] Disable cache for profile:run

### ISSUE THREAD

**Issue by fubarhouse** [seanhamlin/site-audit#221]
In the following excerpt from a Drutiny profile, only one task is completed and the other task is not run.

```
  Drupal8:ModulesDisabled:
    severity: normal
    parameters:
      modules:
        - password_policy
  Drupal8:ModulesDisabled:
    severity: high
    parameters:
      modules:
        - shield
```

It is our assumption that the results are being cached so all following audits using the same Audit will be ignored. Is there a recommended way (or feature) to disable cache for a profile run or at a global level?
