### ISSUE TITLE
[Feature-request] Audit class to check if any specific type of file/directory present

### ISSUE THREAD

**Issue by omkar-pednekar** [seanhamlin/site-audit#292]
Problem Statement:
I want to check if Symbolic links are present or not in a specific location.

In the existing `CodeScanAnalysis` class, we are scanning the only file. We have hardcoded `-type f`. If we want to find symbolic links, we need to set the type to `l`.
Below file types we can find using the find command:
b - block special
c - character special
d - directory
f - regular file
l - symbolic link
p - FIFO
s - socket

Provide the ability to scan/find these types of files.

**Comment by omkar-pednekar** [comment]
PR for this feature: https://github.com/drutiny/drutiny/pull/293

**Comment by omkar-pednekar** [comment]
Some parameter combinations:

- To find Directory:
```
  directory: '%root/'
  maxdepth: 1
  filenames:
    - themes
  type: 'd'
  syntax: twig
  expression: 'has_results ? FAILURE : SUCCESS'
```
- To find Symbolic links
```
  directory: '%root/'
  maxdepth: 1
  exclude:
    - '%root/files'
  type: 'l'
  syntax: twig
  expression: 'has_results ? FAILURE : SUCCESS'
```
- To check existence of specific file:
```
directory: '%root/'
  maxdepth: 1
  filenames:
    - .htaccess
    - index.php
  exclude:
    - '%root/files'
  type: 'f'
  syntax: twig
  expression: 'has_results ? FAILURE : SUCCESS'
```
